production:
  username: manuable
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000
  
development:
  username: manuable
  adapter: postgresql
  database: manuable_development
  password: manuabledev
  pool: 5
  timeout: 5000
  host: localhost

dev_api:
  username: manuable
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

staging:
  username: manuable
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000
