development:
  username: goreorto
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000

dev_api:
  username: goreorto
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

staging:
  username: goreorto
  adapter: postgresql
  database: manuable_development
  password:
  pool: 5
  timeout: 5000
